### ISSUE TITLE
Wrong property `titleId` picked for `UseA11yDialogProps`

### ISSUE THREAD

**Issue by emuecksch-sz** [KittyGiraudel/react-a11y-dialog#302]
Hey everyone,
in your latest changes for Version 7.2.0 there might be a bug.

For `UseA11yDialogProps` type your pick `titleId` instead of `title` which i guess is wrong, because the titleId is generated from the user provided `id` and `title` fields. Can you confirm this?

https://github.com/KittyGiraudel/react-a11y-dialog/blob/main/src/react-a11y-dialog.tsx#L114

Best
Eike

**Comment by KittyGiraudel** [comment]
Hello Eike,

Thanks for reporting an issue. I had a look and it seems that the documentation is wrong. Passing the `title` property to the `useA11yDialog()` hook does nothing. That makes sense, since the point of the hook is to render your own markup, so you don’t need to pass a title to the hook itself. I’ll issue a fix for the docs. :)

**Comment by KittyGiraudel** [comment]
Fixed with https://github.com/KittyGiraudel/react-a11y-dialog/commit/f0d07caae17adf13e51395ccd610f620aefc5401.

**Comment by emuecksch-sz** [comment]
Thank you for explaining and fixing this.
